name: Security with Snyk
on: push

jobs:
  open-source_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Intall npm
        run: |
          cd app
          npm install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.4.0
        continue-on-error: true
        with:
          args: --file=app/package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  container_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build a Docker image
        run: docker build -t vuln-webapp .

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: vuln-webapp
